### ISSUE TITLE
Teste do bot e branco não conta como green.

### ISSUE THREAD

**Issue by yosefben** [emilsonsn/bot-blaze#1]
Oi cara parabéns, muito bom o seu bot de todos que testei e o melhor, vejo que entende bem de classes e funções, tipo nos testes que fiz geralmente em outros bots, a entradas são tipo a cor mais o branco como proteção, e se der o branco conta como green, tipo caso queria implementar só falta a porcentagem de acertos e quantos Loss e Green e G1 e G2 deram, mas sério o bot é ótimo.

**Comment by yosefben** [comment]
> Opa, vw, na verdade já implementei um de adicionar ou não o branco como condição de vitoria, mas ainda não acertou e sobre a função de certos e loss já tem algumas ideias em mente, obrigado pela sugestão. Fico bastante feliz com seu comentário, vlww 🚀

Cara fui sincero muito bom o bot, e tipo quanto tempo tu programa? eu já estudei bem pouco c++ no passado, agora quero ver se domino o python e faça projetos, pode dar umas dicas de estudo no python?

**Comment by emilsonsn** [comment]
Programo a uns 5 anos, porém estou estudando python a um ano. Minha recomendação é dar um fuçada na documentação. 
Sucesso, amigo.
